### ISSUE TITLE
您的博客被日了。。。。

### ISSUE THREAD

**Issue by hfuuss** [FrankFang/best-chinese-front-end-blogs#22]
博客被日了。。。。
http://iwritejs.com

**Comment by EricWong1994** [comment]
> 博客被日了。。。。 http://iwritejs.com

被日，哈哈哈。

**Comment by maybeshewill1** [comment]
看你小人得志的样子，曹尼玛，你以为你爸爸care一个一百年都不用一次的git账号？？？？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 后厂村小王 ***@***.***&gt;
发送时间: 2021年12月10日 17:03
收件人: FrankFang/best-chinese-front-end-blogs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [FrankFang/best-chinese-front-end-blogs] 您的博客被日了。。。。 (#22)





  
博客被日了。。。。 http://iwritejs.com
  
被日，哈哈哈。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EricWong1994** [comment]
> 看你小人得志的样子，曹尼玛，你以为你爸爸care一个一百年都不用一次的git账号？？？？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 后厂村小王 ***@***.***&gt; 发送时间: 2021年12月10日 17:03 收件人: FrankFang/best-chinese-front-end-blogs ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [FrankFang/best-chinese-front-end-blogs] 您的博客被日了。。。。 (#22) 博客被日了。。。。 http://iwritejs.com 被日，哈哈哈。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
这是啥仇啥怨，咋都跑到github来骂来了，

**Comment by FrankFang** [comment]
谢谢提醒，已经换域名了 fangyinghang.com
